<<<<<<< HEAD
# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# Split configuration 
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_WIRED=y
#Display 
CONFIG_ZMK_DISPLAY=y
# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
=======
# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# Split configuration 
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_WIRED=y
#Display 
CONFIG_ZMK_DISPLAY=y
# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
>>>>>>> 1354a2571150a55eeb93091d84b18f7375253020
CONFIG_ZMK_STUDIO_LOCKING=n