# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# Split configuration 
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
#CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=n
#SPlit Options
#CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
#CONFIG_ZMK_SPLIT_WIRED=y
#Display 
CONFIG_ZMK_DISPLAY=n
# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
#una recomendacion de glok
CONFIG_ZMK_BLE=y
# === LOGGING PARA DIAGNÓSTICO ===
#CONFIG_ZMK_LOGGING=y
# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10